### PR TITLE
Remove mkdirp.

### LINKED ISSUE #124: Remove mkdirp?
Node.js >= 10.12.0 supports a recursive option https://nodejs.org/docs/latest-v10.x/api/fs.html#fs_fs_mkdir_path_options_callback

> v10.12.0 | The second argument can now be an options object with recursive and mode properties.

Just opening the issue for the future :)

### PR DESCRIPTION
**Pull request by XhmikosR**
Requires Node.js >= 10.12.0.

Requires #123 merged first and I only tested it quickly.

Fixes #124

### CODE REVIEW

**Comment by olegskl** [comment]
Needs a rebase I think.

**Comment by XhmikosR** [comment]
Not sure if you wanted more tests added, this was the easiest solution.

**Comment by olegskl** [comment]
I think the tests are okay. I'm just a little bummed that the `recursive` option is not in Node v10.0.0. Totally forgot that it needs v10.12.0.

**Comment by XhmikosR** [comment]
Yup. Your call, it's not a big improvement anyway.

**Comment by olegskl** [comment]
We can do it like this:
 1. Release v12.0.0 with mkdirp and node >=10.0.0
 2. Release v13.0.0 without mkdirp and node >=10.12.0

**Comment by XhmikosR** [comment]
I'm not sure I see any gain. I mean, it seems more confusing that way?

**Comment by olegskl** [comment]
I will merge and release as v13. If anyone complains, I will release v12 with node >=10.0.0 and without mkdirp.

**Comment by olegskl** [comment]
Released as [v13.0.0](https://github.com/olegskl/gulp-stylelint/releases/tag/v13.0.0). Thanks! 🙇

**Pull request merged**
