### PR TITLE
docs(readme): add dependencies status badge

### PR DESCRIPTION
**Pull request by olegskl**
Having this badge will remind me to update dependencies when they get out of date, because otherwise I will definitely forget to do it...

### CODE REVIEW

**Comment by jeddy3** [comment]
Perhaps consider https://greenkeeper.io/ as well? The `linter-stylelint` guys seem to be [using it](https://github.com/AtomLinter/linter-stylelint/pulls?q=is%3Apr+is%3Aclosed+label%3Agreenkeeper) to keep their version of stylelint up to date

**Comment by olegskl** [comment]
It seems that usage of greenkeeper requires monthly payments beyond a single open-source repository. I'm a bit hesitant 😕

**Comment by jeddy3** [comment]
The website says it's free "*unlimited* public repos". Am I misunderstanding it?

**Comment by olegskl** [comment]
Ah, no-no, you're right. I misread the terms. It's "Unlimited public repos and 1 free **private** repo". I'll take a closer look this evening.

**Pull request merged**
