### PR TITLE
feat(lib): use formatters instead of reporters

### PR DESCRIPTION
**Pull request by olegskl**
- New API (see README)
 - Uses stylelint formatters instead of reporters with individual writing logic
 - Better test coverage

### CODE REVIEW

**Comment by olegskl** [comment]
This PR covers #3 and #4 with breaking API changes (to be released as v1).
Missing stylelint-text-formatter though.

**Comment by davidtheclark** [comment]
Looks great to me! Are you happy with how it came out?

**Comment by olegskl** [comment]
I still want to add a feature (not directly related to stylelint itself) and write more tests.
In the meanwhile I can publish it as v1 beta.

**Comment by davidtheclark** [comment]
Need any help to get v1 out?

**Comment by olegskl** [comment]
I'll get to it tomorrow. Was busy lately.

**Comment by davidtheclark** [comment]
Cool, I understand, just checking in :)

**Pull request merged**
