### PR TITLE
Update to support StyleLint 6.5.X

### PR DESCRIPTION
**Pull request by Arkkimaagi**
I'd like to keep stylelint updated. :)

### CODE REVIEW

**Comment by Arkkimaagi** [comment]
I think if this is approved, this can be closed: https://github.com/olegskl/gulp-stylelint/pull/27

**Comment by Arkkimaagi** [comment]
Here are the docs: https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#651

**Comment by olegskl** [comment]
Hello and thanks for taking your time to do this MR.

Technically this change isn't necessary because a dependency on ^6.2.1 basically means 6.x.x, thus people installing gulp-stylelint automatically get the latest v6 stylelint.

**Comment by Arkkimaagi** [comment]
I was just reading about that, it was an error on my part. Sorry for the hassle. :)

**Comment by Arkkimaagi** [comment]
The issue was that we started using npm-shrinkwrap and I was not familiar enough with it to understand what it meant in this context. :)

**Pull request closed without merging**
