### PR TITLE
chore(package): update stylelint dependency to v6

### PR DESCRIPTION
**Pull request by chatii2412**
`stylelint` was [updated to 6.0.0](https://github.com/stylelint/stylelint/releases/tag/6.0.0) yesterday.
Please review this.

### CODE REVIEW

**Comment by olegskl** [comment]
Thanks for the MR! This will be released in v2 due to breaking changes in stylelint.
Currently there seems to be an error reporting issue in stylelint v6, so I'll need to postpone merging this (hopefully the wait won't be long).

**Comment by davidtheclark** [comment]
Just released 6.0.2 which I hope fixes thid.

**Comment by olegskl** [comment]
@chatii2412 could you please change version to **^6.0.2** and commit title to

> chore(package): update stylelint dependency to v6

and I will merge. Thanks in advance.

**Comment by chris-morgan** [comment]
Point of curiosity (from someone not especially familiar with npm or gulp conventions): why does gulp-stylelint have a dependency on `stylelint@^5.4.0`, requiring a major version bump to upgrade to `^6.0.2`, rather than a peerDependency on `stylelint@^5.4.0` which could then reasonably be changed to `stylelint@>5.4.0,<7.0.0` without needing a major version bump in gulp-stylelint itself?

**Comment by chatii2412** [comment]
@olegskl
I changed dependency version to `^6.0.3` and the commit message, too.
And `stylelint`'s patch version is keep changing now, you can just close it and update yourself.
Thanks.

**Comment by olegskl** [comment]
@chatii2412 thanks, merged and released this morning.
@chris-morgan both approaches seem to be valid. Personally, I just think it's easier for users to download gulp-stylelint and don't bother figuring out which peer dependencies need to be installed as well. I'm open to change if there's sufficient demand for using stylelint as a peer dependency.

**Pull request merged**
