### PR TITLE
Update devDependencies and flatten deps tree.

### PR DESCRIPTION
**Pull request by XhmikosR**
I will need to rebase this after #114 so just ping me @olegskl 

#114:
>added 932 packages in 6.219s

this patch:
>added 762 packages in 4.754s

### CODE REVIEW

**Comment by XhmikosR** [comment]
@olegskl should be ready to merge. Please release a new version after this is merged too, thanks!

**Comment by olegskl** [comment]
I can incorporate it into v10. Do you prefer it to be in 10.0.1?

**Comment by XhmikosR** [comment]
No, no, just merge it now :)

**Comment by XhmikosR** [comment]
@olegskl you should enable [automated security fixes](https://help.github.com/en/articles/configuring-automated-security-fixes) for your repos :)

**Pull request merged**
